[package]
name = "rstest-bdd"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description.workspace = true
homepage.workspace = true
repository.workspace = true
readme = "../../README.md"
keywords.workspace = true
categories.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
gherkin.workspace = true
inventory.workspace = true
regex.workspace = true
thiserror = { version = "1.0", default-features = false }
hashbrown = "0.15"

[dev-dependencies]
rstest.workspace = true
rstest-bdd-macros = { path = "../rstest-bdd-macros" }

