[package]
name = "rstest-bdd"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]

gherkin = { version = "0.14", default-features = false, features = ["parser"] }
inventory = ">=0.3, <0.4"
regex = "1.11.1"
thiserror = "1.0"

[dev-dependencies]
rstest = ">=0.18, <0.19"
rstest-bdd-macros = { path = "../rstest-bdd-macros" }

