[package]
name = "rstest-bdd"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description.workspace = true
homepage.workspace = true
repository.workspace = true
readme = "README.md"
keywords.workspace = true
categories.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
gherkin.workspace = true
inventory.workspace = true
regex.workspace = true
thiserror.workspace = true
hashbrown = "0.15"
serde.workspace = true
serde_json.workspace = true
ctor.workspace = true

[dev-dependencies]
rstest.workspace = true
rstest-bdd-macros.workspace = true

