[package]
name = "rstest-bdd"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]

inventory = ">=0.3, <0.4"

[dev-dependencies]
rstest = ">=0.18, <0.19"
rstest-bdd-macros = { path = "../rstest-bdd-macros" }

