[package]
name = "rstest-bdd"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]

inventory = ">=0.3, <0.4"
regex = "1.11.1"
thiserror = "1.0"
phf = { version = "0.11", features = ["macros"] }

[dev-dependencies]
rstest = ">=0.18, <0.19"
rstest-bdd-macros = { path = "../rstest-bdd-macros" }

