"""Contract tests for the pull-request CodeScene coverage gate.

The shared actions generate and check the coverage report. This module
asserts rstest-bdd's declarative caller contract so the report-producing
matrix leg, least-privilege checkout and step ordering cannot drift
silently. Each shared action must be pinned to a full commit SHA, but the
SHA value of the coverage generator is owned by Dependabot and is
deliberately not asserted; the CodeScene uploader's is, because that
revision carries the CLI manifest this repository trusts.

Run via ``make test-workflow-contracts``.
"""

import re
from pathlib import Path

import pytest
import yaml

WORKFLOW_PATH = Path(__file__).resolve().parents[2] / ".github" / "workflows" / "ci.yml"

GENERATE_COVERAGE_USES_RE = re.compile(
    r"^leynos/shared-actions/\.github/actions/generate-coverage@[0-9a-f]{40}$"
)
CODESCENE_COVERAGE_USES_RE = re.compile(
    r"^leynos/shared-actions/\.github/actions/upload-codescene-coverage@"
    r"[0-9a-f]{40}$"
)
CODESCENE_UPLOAD_GUARD = (
    "matrix.os == 'ubicloud-standard-2' && "
    "github.event_name == 'push' && "
    "github.ref == 'refs/heads/main' && "
    "env.CS_ACCESS_TOKEN != ''"
)
EXPECTED_CODESCENE_UPLOAD_INPUTS = {
    "format": "cobertura",
    "access-token": "${{ env.CS_ACCESS_TOKEN }}",
}
CODESCENE_GUARD = (
    "matrix.os == 'ubicloud-standard-2' && "
    "github.event_name == 'pull_request' && "
    "env.CS_ACCESS_TOKEN != ''"
)
EXPECTED_GENERATOR_INPUTS = {
    "cache-provider": "external",
    "output-path": "coverage.xml",
    "format": "cobertura",
    "all-features": "true",
    "all-targets": "true",
    "doctests": "true",
    "use-cargo-nextest": "true",
    "pytest-workers": "",
    "with-ratchet": "true",
}
EXPECTED_CODESCENE_INPUTS = {
    "format": "cobertura",
    "mode": "check",
    "project-url": "https://api.codescene.io/v2/projects/69391",
    "access-token": "${{ env.CS_ACCESS_TOKEN }}",
}
EXPECTED_CARGO_WAIT_TIMEOUT = "6600"


def _load() -> dict[str, object]:
    """Parse the continuous-integration workflow."""
    return yaml.safe_load(WORKFLOW_PATH.read_text(encoding="utf-8"))


def _build_test_job(workflow: dict[str, object]) -> dict[str, object]:
    """Return the build-test matrix job."""
    jobs = workflow.get("jobs")
    assert isinstance(jobs, dict), "the workflow must declare a jobs mapping"
    build_test = jobs.get("build-test")
    assert isinstance(build_test, dict), "jobs.build-test must be a mapping"
    return build_test


def _steps(build_test_job: dict[str, object]) -> list[dict[str, object]]:
    """Return the build-test steps as mappings."""
    steps = build_test_job.get("steps")
    assert isinstance(steps, list), "jobs.build-test.steps must be a list"
    assert all(isinstance(step, dict) for step in steps), (
        "every jobs.build-test step must be a mapping"
    )
    return steps


def _named_step(steps: list[dict[str, object]], name: str) -> dict[str, object]:
    """Return the uniquely named workflow step."""
    matches = [step for step in steps if step.get("name") == name]
    assert len(matches) == 1, f"expected one {name!r} step, found {len(matches)}"
    return matches[0]


@pytest.fixture(scope="module")
def workflow() -> dict[str, object]:
    """Parse the workflow file once for the module."""
    return _load()


@pytest.fixture(scope="module")
def build_test_job(workflow: dict[str, object]) -> dict[str, object]:
    """Return the build-test job once for the module."""
    return _build_test_job(workflow)


@pytest.fixture(scope="module")
def build_test_steps(
    build_test_job: dict[str, object],
) -> list[dict[str, object]]:
    """Return the build-test steps once for the module."""
    return _steps(build_test_job)


def test_linux_generator_emits_the_canonical_report(
    build_test_steps: list[dict[str, object]],
) -> None:
    """The sole Linux execution must emit canonical Cobertura output."""
    generator = _named_step(build_test_steps, "Test and Measure Coverage (Linux)")
    assert GENERATE_COVERAGE_USES_RE.match(str(generator.get("uses") or "")), (
        "the Linux coverage generator must use the shared generate-coverage "
        "action pinned to a full commit SHA"
    )
    assert generator.get("if") == "${{ runner.os == 'Linux' }}", (
        "the canonical report must be generated by the sole Linux lane"
    )
    assert generator.get("with") == EXPECTED_GENERATOR_INPUTS, (
        "the Linux generator must preserve its canonical report and ratchet inputs"
    )


@pytest.mark.parametrize(
    ("step_name", "lane"),
    [
        ("Test and Measure Coverage (Linux)", "Linux"),
        ("Test and Measure Coverage (Windows, default features)", "Windows"),
        ("Test and Measure Coverage (Windows, strict validation)", "Windows"),
    ],
)
def test_coverage_steps_budget_a_cold_instrumented_build(
    build_test_steps: list[dict[str, object]],
    step_name: str,
    lane: str,
) -> None:
    """Each coverage lane must budget the watchdog for a cold instrumented build."""
    step = _named_step(build_test_steps, step_name)
    env = step.get("env")
    assert isinstance(env, dict), f"the {lane} coverage step must declare env"
    assert env.get("RUN_RUST_CARGO_WAIT_TIMEOUT") == EXPECTED_CARGO_WAIT_TIMEOUT, (
        f"the {lane} coverage step must size the cargo watchdog for a cold "
        "sccache store; the watchdog exists to catch a hang, not a cold build"
    )


def test_codescene_step_uses_the_approved_check_contract(
    build_test_steps: list[dict[str, object]],
) -> None:
    """The PR gate must use a SHA-pinned action, the guard and the inputs."""
    check = _named_step(build_test_steps, "Check coverage against CodeScene gates")
    assert CODESCENE_COVERAGE_USES_RE.match(str(check.get("uses") or "")), (
        "the CodeScene gate must be pinned to a full commit SHA"
    )
    assert check.get("env") == {"CS_ACCESS_TOKEN": "${{ secrets.CS_ACCESS_TOKEN }}"}, (
        "the CodeScene token must be scoped explicitly to the check step"
    )
    assert check.get("if") == CODESCENE_GUARD, (
        "the CodeScene gate must run only on the report-producing pull-request leg"
    )
    assert check.get("with") == EXPECTED_CODESCENE_INPUTS, (
        "the CodeScene gate must retain the exact mode-check input contract"
    )


def test_codescene_gate_has_read_only_full_history_checkout(
    build_test_job: dict[str, object],
    build_test_steps: list[dict[str, object]],
) -> None:
    """The changed-line gate needs least privilege and the merge-base history."""
    assert build_test_job.get("permissions") == {"contents": "read"}, (
        "jobs.build-test permissions must remain exactly contents: read"
    )
    checkout = _named_step(build_test_steps, "Checkout")
    checkout_inputs = checkout.get("with")
    assert isinstance(checkout_inputs, dict), "the checkout step must declare inputs"
    assert checkout_inputs.get("fetch-depth") == 0, (
        "the checkout must retain full history for cs-coverage check"
    )


def test_codescene_gate_follows_report_verification_before_publish(
    build_test_steps: list[dict[str, object]],
) -> None:
    """The check must consume a verified report before the publish dry run."""
    names = [step.get("name") for step in build_test_steps]
    verify_index = names.index("Verify coverage output exists")
    check_index = names.index("Check coverage against CodeScene gates")
    publish_index = names.index("Publish dry run")
    assert verify_index < check_index < publish_index, (
        "the CodeScene check must follow report verification and precede publishing"
    )


def test_codescene_reports_split_by_event_in_one_lane() -> None:
    """One lane checks pull requests and uploads the analysed trunk branch."""
    steps = _steps(_build_test_job(_load()))
    codescene_steps = [
        step
        for step in steps
        if CODESCENE_COVERAGE_USES_RE.match(str(step.get("uses") or ""))
    ]
    assert len(codescene_steps) == 2, (
        "expected a pull-request check and a trunk upload, found "
        f"{len(codescene_steps)} CodeScene steps"
    )
    check, upload = codescene_steps
    assert check.get("with") == EXPECTED_CODESCENE_INPUTS, (
        "the pull-request step must use mode: check"
    )
    assert upload.get("with") == EXPECTED_CODESCENE_UPLOAD_INPUTS, (
        "CodeScene accepts an upload only for an analysed branch, so the trunk "
        "step must omit mode and project-url"
    )
    assert upload.get("if") == CODESCENE_UPLOAD_GUARD, (
        "the upload must run only on the report-producing lane on trunk"
    )


#: The uploader revision whose committed ``cli-manifest.json`` is the trust
#: anchor for the CodeScene CLI archive. Named as an allowlist rather than
#: matched as "any full SHA": a different revision is a different manifest,
#: whatever the shape of its identifier.
UPLOADER_PIN = "a5765019912a8ab6882b12db049c7cde635f3a85"
UPLOADER_ACTION = "leynos/shared-actions/.github/actions/upload-codescene-coverage"
#: The repository variable that held the installer script's digest.
DEPRECATED_DIGEST_VARIABLE = "CODESCENE_CLI_SHA256"
#: The dispatch workflow whose only output was that variable.
DIGEST_REFRESH_WORKFLOW = "get-codescene-sha.yml"

WORKFLOW_DIRECTORY = WORKFLOW_PATH.parent


def _workflow_texts() -> dict[str, str]:
    """Return every workflow file's raw text, keyed by file name.

    Read as text rather than parsed. The strings refused below read the same
    in a comment as in a value, and a comment carrying one is an instruction
    to a later reader to reintroduce the other.

    Returns
    -------
    dict[str, str]
        Workflow file name to file contents.
    """
    texts = {
        path.name: path.read_text(encoding="utf-8")
        for path in sorted(WORKFLOW_DIRECTORY.iterdir())
        if path.suffix in {".yml", ".yaml"}
    }
    assert texts, (
        "no workflow files were read, so every assertion over them would hold vacuously"
    )
    return texts


def test_no_workflow_passes_the_deprecated_installer_checksum() -> None:
    """Refuse the input the uploader rejects outright.

    From shared-actions ``f68e8e2e`` a non-empty ``installer-checksum`` exits
    the action with a hard failure. Trunk stayed green only because the
    repository variable feeding it happened to be empty, so the defect was
    latent rather than absent, and it fires the moment the variable is set.
    """
    offending = sorted(
        name for name, text in _workflow_texts().items() if "installer-checksum" in text
    )

    assert not offending, (
        "installer-checksum is rejected when non-empty; pass nothing, because "
        "the uploader's committed manifest is the trust anchor and "
        f"archive-checksum can only repeat its digest: {offending}"
    )


def test_no_workflow_reads_the_deprecated_digest_variable() -> None:
    """Leave no workflow reading or refreshing a value nothing consumes.

    ``installer-checksum`` was the variable's only consumer. A workflow still
    reading it feeds a rejected input, which fails only when the uploader
    runs; one still refreshing it maintains dead state, which never fails at
    all and so is invisible without this rule.
    """
    offending = sorted(
        name
        for name, text in _workflow_texts().items()
        if DEPRECATED_DIGEST_VARIABLE in text
    )

    assert not offending, (
        f"no workflow may read or refresh {DEPRECATED_DIGEST_VARIABLE}; the "
        f"uploader pins the CLI through its own manifest: {offending}"
    )


def test_the_digest_refresh_workflow_is_absent() -> None:
    """Keep the dispatch that maintained the dead variable out of the tree.

    This repository has never carried it. The rule is estate-wide, so a
    template sync re-adding the workflow would otherwise reintroduce the
    variable with nothing here to notice.
    """
    assert not (WORKFLOW_DIRECTORY / DIGEST_REFRESH_WORKFLOW).exists(), (
        f"{DIGEST_REFRESH_WORKFLOW} refreshes a variable nothing reads; it "
        "must not exist"
    )


def test_every_uploader_call_is_on_the_approved_revision() -> None:
    """Hold every uploader call to the revision carrying the manifest.

    A full-SHA rule alone is satisfied by any revision, including the ones
    whose unpinned ``cs-coverage`` could not parse its own Cobertura output.
    The approved pin is therefore named, and the reference set is asserted
    non-empty first so that deleting the calls cannot satisfy the rule.
    """
    references = sorted(
        f"{name}:{line.strip()}"
        for name, text in _workflow_texts().items()
        for line in text.splitlines()
        if f"{UPLOADER_ACTION}@" in line
    )

    assert references, "this repository must call the CodeScene uploader"
    wrong = [
        reference
        for reference in references
        if f"{UPLOADER_ACTION}@{UPLOADER_PIN}" not in reference
    ]
    assert not wrong, f"every uploader call must be pinned to {UPLOADER_PIN}: {wrong}"
