"""Contract tests for the pull-request CodeScene coverage gate.

The shared actions generate and check the coverage report. This module
asserts rstest-bdd's declarative caller contract so the report-producing
matrix leg, least-privilege checkout and step ordering cannot drift
silently. Each shared action must be pinned to a full commit SHA, but the
SHA value itself is owned by Dependabot and is deliberately not asserted.

Run via ``make test-workflow-contracts``.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest
import yaml

WORKFLOW_PATH = Path(__file__).resolve().parents[2] / ".github" / "workflows" / "ci.yml"

GENERATE_COVERAGE_USES_RE = re.compile(
    r"^leynos/shared-actions/\.github/actions/generate-coverage@[0-9a-f]{40}$"
)
CODESCENE_COVERAGE_USES_RE = re.compile(
    r"^leynos/shared-actions/\.github/actions/upload-codescene-coverage@"
    r"[0-9a-f]{40}$"
)
CODESCENE_GUARD = (
    "matrix.os == 'ubuntu-latest' && "
    "matrix.features == '' && "
    "github.event_name == 'pull_request' && "
    "env.CS_ACCESS_TOKEN != ''"
)
EXPECTED_GENERATOR_INPUTS = {
    "output-path": "coverage.xml",
    "format": "cobertura",
    "features": (
        "rstest-bdd/diagnostics "
        "rstest-bdd-macros/compile-time-validation "
        "rstest-bdd-server/test-support"
    ),
    "with-default-features": "${{ matrix.with-default-features }}",
    "use-cargo-nextest": "${{ matrix.use-nextest }}",
    "pytest-workers": "",
    "with-ratchet": (
        "${{ (matrix.os == 'ubuntu-latest' && matrix.features == '') "
        "&& 'true' || 'false' }}"
    ),
}
EXPECTED_CODESCENE_INPUTS = {
    "format": "cobertura",
    "mode": "check",
    "project-url": "https://api.codescene.io/v2/projects/69391",
    "access-token": "${{ env.CS_ACCESS_TOKEN }}",
    "installer-checksum": "${{ vars.CODESCENE_CLI_SHA256 }}",
}


def _load() -> dict[str, object]:
    """Parse the continuous-integration workflow."""
    return yaml.safe_load(WORKFLOW_PATH.read_text(encoding="utf-8"))


def _build_test_job(workflow: dict[str, object]) -> dict[str, object]:
    """Return the build-test matrix job."""
    jobs = workflow.get("jobs")
    assert isinstance(jobs, dict), "the workflow must declare a jobs mapping"
    build_test = jobs.get("build-test")
    assert isinstance(build_test, dict), "jobs.build-test must be a mapping"
    return build_test


def _steps(build_test_job: dict[str, object]) -> list[dict[str, object]]:
    """Return the build-test steps as mappings."""
    steps = build_test_job.get("steps")
    assert isinstance(steps, list), "jobs.build-test.steps must be a list"
    assert all(isinstance(step, dict) for step in steps), (
        "every jobs.build-test step must be a mapping"
    )
    return steps


def _named_step(steps: list[dict[str, object]], name: str) -> dict[str, object]:
    """Return the uniquely named workflow step."""
    matches = [step for step in steps if step.get("name") == name]
    assert len(matches) == 1, f"expected one {name!r} step, found {len(matches)}"
    return matches[0]


@pytest.fixture(scope="module")
def workflow() -> dict[str, object]:
    """Parse the workflow file once for the module."""
    return _load()


@pytest.fixture(scope="module")
def build_test_job(workflow: dict[str, object]) -> dict[str, object]:
    """Return the build-test job once for the module."""
    return _build_test_job(workflow)


@pytest.fixture(scope="module")
def build_test_steps(
    build_test_job: dict[str, object],
) -> list[dict[str, object]]:
    """Return the build-test steps once for the module."""
    return _steps(build_test_job)


def test_default_feature_generator_emits_the_canonical_report(
    build_test_steps: list[dict[str, object]],
) -> None:
    """The ratcheted Linux leg must emit canonical Cobertura output."""
    generator = _named_step(build_test_steps, "Test and Measure Coverage (no features)")
    assert GENERATE_COVERAGE_USES_RE.match(str(generator.get("uses") or "")), (
        "the no-feature coverage generator must use the shared generate-coverage "
        "action pinned to a full commit SHA"
    )
    assert generator.get("if") == "${{ matrix.coverage && matrix.features == '' }}", (
        "the canonical report must be generated by the empty-feature matrix leg"
    )
    assert generator.get("with") == EXPECTED_GENERATOR_INPUTS, (
        "the no-feature generator must preserve its canonical report and ratchet inputs"
    )


def test_codescene_step_uses_the_approved_check_contract(
    build_test_steps: list[dict[str, object]],
) -> None:
    """The PR gate must use a SHA-pinned action, the guard and the inputs."""
    check = _named_step(build_test_steps, "Check coverage against CodeScene gates")
    assert CODESCENE_COVERAGE_USES_RE.match(str(check.get("uses") or "")), (
        "the CodeScene gate must be pinned to a full commit SHA"
    )
    assert check.get("env") == {"CS_ACCESS_TOKEN": "${{ secrets.CS_ACCESS_TOKEN }}"}, (
        "the CodeScene token must be scoped explicitly to the check step"
    )
    assert check.get("if") == CODESCENE_GUARD, (
        "the CodeScene gate must run only on the report-producing pull-request leg"
    )
    assert check.get("with") == EXPECTED_CODESCENE_INPUTS, (
        "the CodeScene gate must retain the exact mode-check input contract"
    )


def test_codescene_gate_has_read_only_full_history_checkout(
    build_test_job: dict[str, object],
    build_test_steps: list[dict[str, object]],
) -> None:
    """The changed-line gate needs least privilege and the merge-base history."""
    assert build_test_job.get("permissions") == {"contents": "read"}, (
        "jobs.build-test permissions must remain exactly contents: read"
    )
    checkout = _named_step(build_test_steps, "Checkout")
    checkout_inputs = checkout.get("with")
    assert isinstance(checkout_inputs, dict), "the checkout step must declare inputs"
    assert checkout_inputs.get("fetch-depth") == 0, (
        "the checkout must retain full history for cs-coverage check"
    )


def test_codescene_gate_follows_report_verification_before_publish(
    build_test_steps: list[dict[str, object]],
) -> None:
    """The check must consume a verified report before the publish dry run."""
    names = [step.get("name") for step in build_test_steps]
    verify_index = names.index("Verify coverage output exists")
    check_index = names.index("Check coverage against CodeScene gates")
    publish_index = names.index("Publish dry run")
    assert verify_index < check_index < publish_index, (
        "the CodeScene check must follow report verification and precede publishing"
    )


def test_codescene_pr_report_has_one_check_and_no_upload(
    build_test_steps: list[dict[str, object]],
) -> None:
    """The PR workflow checks one report and never uploads branch coverage."""
    codescene_steps = [
        step
        for step in build_test_steps
        if CODESCENE_COVERAGE_USES_RE.match(str(step.get("uses") or ""))
    ]
    assert len(codescene_steps) == 1, (
        f"expected one CodeScene coverage step, found {len(codescene_steps)}"
    )
    assert codescene_steps[0].get("with") == EXPECTED_CODESCENE_INPUTS, (
        "the sole PR CodeScene step must use mode: check, never upload"
    )
