[package]
name = "rstest-bdd-macros"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"

[lints]
workspace = true

[lib]
proc-macro = true


[dependencies]
proc-macro2 = ">=1.0, <2.0"
quote = ">=1.0, <2.0"
syn = { version = ">=2.0, <3.0", features = ["full"] }
rstest-bdd = { path = "../rstest-bdd" }
gherkin = { version = ">=0.14, <0.15", default-features = false, features = ["parser"] }

[dev-dependencies]
trybuild = ">=1.0, <2.0"
once_cell = ">=1.18, <2.0"
rstest = ">=0.18, <0.19"
