[package]
name = "rstest-bdd-macros"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "Procedural macros for the rstest-bdd testing framework."
homepage.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[lib]
proc-macro = true


[dependencies]
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true
rstest-bdd.workspace = true
gherkin.workspace = true

[dev-dependencies]
trybuild.workspace = true
once_cell.workspace = true
rstest.workspace = true
serial_test.workspace = true
